export const sounds = [
  {
    id: 'birds',
    name: 'Birds',
    icon: 'fa-crow',
    colour: 'grey-800',
    file: 'birds.mp3',
    description: 'Gentle bird song',
  },
  {
    id: 'crickets',
    name: 'Crickets',
    icon: 'fa-bug',
    colour: 'grey-800',
    file: 'crickets.mp3',
    description: 'Crickets chirping',
  },
  {
    id: 'fire',
    name: 'Fire',
    icon: 'fa-fire',
    colour: 'grey-800',
    file: 'fire.mp3',
    description: 'Fire raging',
  },
  {
    id: 'pub',
    name: 'Pub',
    icon: 'fa-glass-water',
    colour: 'grey-800',
    file: 'pub-800',
    description: 'Crowded pub',
  },
  {
    id: 'thunder',
    name: 'Thunder',
    icon: 'fa-cloud-bolt',
    colour: 'grey-800',
    file: 'thunder.mp3',
    description: 'Rumbling thunder',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: 'grey-800',
    file: 'traffic.mp3',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: 'grey-800',
    file: 'water.mp3',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: 'grey-800',
    file: 'waves.mp3',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: 'grey-800',
    file: 'wind.mp3',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: 'grey-800',
    file: 'wooden-blocks.mp3',
    description: '',
  },
]