export const sounds = [
  {
    id: 'birds',
    name: 'Birds',
    icon: 'fa-solid fa-crow',
    colour: 'grey-800',
    file: 'birds.mp3',
    description: 'Gentle bird song',
  },
  {
    id: 'crickets',
    name: 'Crickets',
    icon: 'fa-solid fa-bug',
    colour: 'grey-800',
    file: 'crickets.mp3',
    description: 'Crickets chirping',
  },
  {
    id: 'fire',
    name: 'Fire',
    icon: 'fa-solid fa-fire',
    colour: 'grey-800',
    file: 'fire.mp3',
    description: 'Fire raging',
  },
  {
    id: 'pub',
    name: 'Pub',
    icon: 'fa-solid fa-glass-water',
    colour: 'grey-800',
    file: 'pub-800',
    description: 'Crowded pub',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: '',
    file: '',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: '',
    file: '',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: '',
    file: '',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: '',
    file: '',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: '',
    file: '',
    description: '',
  },
  {
    id: '',
    name: '',
    icon: '',
    colour: '',
    file: '',
    description: '',
  },
]